### PR TITLE
Fix `stripWWW` option

### LINKED ISSUE #38: stripWWW strips domains too
```js
normalize("www.com")
//-> http://com
```

This can be rectified with [strip-www](https://npmjs.com/strip-www).

### PR DESCRIPTION
**Pull request by szmarczak**
Fixes #38

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -85,7 +85,8 @@ module.exports = (urlString, opts) => {
 		urlObj.hostname = urlObj.hostname.replace(/\.$/, '');
 
 		// Remove `www.`
-		if (opts.stripWWW) {
+		// eslint-disable-next-line no-useless-escape
+		if (opts.stripWWW && /^www\.([a-z\-0-9]{2,63})\.([a-z\.]{2,5})$/.test(urlObj.hostname)) {
```
Comment (sindresorhus) [inline index.js]: `0-9` => `\d`

Comment (sindresorhus) [reply index.js]: Can you add a short comment about what the `2,63` and `2,5` numbers mean?

Comment (szmarczak) [reply index.js]: Yeah, but first I need to get some sleep :) (IMO it's obvious it represents min and max length :P but yeah, in case someone doesn't know ;) )

Comment (sindresorhus) [reply index.js]: I don't mean what they mean in regex, I mean, for example, why it's 63 in length.

Comment (szmarczak) [reply index.js]: I'm very lazy :P https://en.m.wikipedia.org/wiki/Hostname#Restrictions_on_valid_host_names

Comment (stevenvachon) [reply index.js]: This has no international support.
