### PR TITLE
Fix encoding consistency with sorted and non-sorted URL parameters

### LINKED ISSUE #149: sortQueryParameters encodes the query string
Is it supposed to be like this?

**sortQueryParameters: true**

```js
normalizeUrl('http://sindresorhus.com/?url=http://example.com', {
    sortQueryParameters: true
});
//=> 'http://sindresorhus.com/?url=http%3A%2F%2Fexample.com'
```

**sortQueryParameters: false**

```js
normalizeUrl('http://sindresorhus.com/?url=http://example.com', {
    sortQueryParameters: false
});
//=> 'http://sindresorhus.com/?url=http://example.com'
```

### PR DESCRIPTION
**Pull request by ludofischer**
Fix #149

Currently `normalize-url` encodes URL parameters when `sortQueryParameters` is `true` and leaves them as they are when not. This behaviour is confusing as a user would not expect sorting the parameters to affect the encoding. This PR tries to ensure the search parameters are always decoded, since `normalize-url` already always decodes the pathname and does not intend to sanitize the URL; https://github.com/sindresorhus/normalize-url/blob/6ea4038783d298d499583db07a820e5ca8ff2721/index.js#L160

### CODE REVIEW

**Comment by sindresorhus** [comment]
This really sounds like a WHATWG URL bug. It should always be consistent about encoding whether or not `.sort()` is called. If you can only reproduce this in Node.js, I recommend opening an issue on https://github.com/nodejs/node, otherwise https://github.com/whatwg/url

**Comment by sindresorhus** [comment]
This really sounds like a WHATWG URL bug. It should always be consistent about encoding whether or not `.sort()` is called. If you can only reproduce this in Node.js, I recommend opening an issue on https://github.com/nodejs/node, otherwise https://github.com/whatwg/url

File: index.js [hunk 1]
```diff
@@ -208,6 +208,11 @@ export default function normalizeUrl(urlString, options) {
 		urlObject.searchParams.sort();
 	}
 
+	// Decode query parameters
+	try {
+		urlObject.search = decodeURIComponent(urlObject.search);
```
Comment (sindresorhus) [inline index.js:213]: Since the search components are unencoded when `.sort()` is not called, this will potentially decode encoded character where the encoding is meant to be preserved. You could potentially only decode when `!options.sortQueryParameters`, but I think the encoding inconsistency is a bug in the URL implementation and it would be risky to depend on it staying like that.

**Comment by ludofischer** [comment]
See also https://github.com/whatwg/url/issues/478 where they decide to keep the current `searchParams` behaviour.
Given that `searchParams` modifies the input by design and the working group does not seem to want to change it, would it be preferable to avoid using it altogether?

**Comment by sindresorhus** [comment]
> Given that searchParams modifies the input by design and the working group does not seem to want to change it, would it be preferable to avoid using it altogether?

There's no easy way to avoid it as we need to keep the sort support and I don't want to bring in another library just for that.

**Comment by sindresorhus** [comment]
> You could potentially only decode when !options.sortQueryParameters

I guess this is the best option then.

**Comment by ludofischer** [comment]
> > You could potentially only decode when !options.sortQueryParameters
> 
> I guess this is the best option then.

I've pushed an additional commit to check if the parameters have been sorted before decoding.

**Comment by psamusev** [comment]
The current behavior of 
`urlObject.pathname = decodeURI(urlObject.pathname); ` 
doesn't work as expected. Since URL automatically always encode any value that we set, according to https://developer.mozilla.org/en-US/docs/Web/API/URL

**Comment by sindresorhus** [comment]
@psamusev It's better to open a new issue instead of commenting on an old pull request. Submitting a failing test would be even better.

**Comment by psamusev** [comment]
@sindresorhus sure, created https://github.com/sindresorhus/normalize-url/issues/165
